In [2]:
#the logistic regression model to predict if a person will be present or absent for work 
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import tensorflow as tf 
sns.set()

In [3]:
preprocess = pd.read_csv('Absenteeism_preprocessed.csv')
preprocess.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          4  
1               31          0         1    0                          0  
2               31          0         0    0                          2  
3               24          0         2    0                          4  
4               30          0         2    1                          2

In [4]:
#create the targets 
#every-value below the median is condiered normal 
#every-value above the median is considered excecess in terms of hours absent 
preprocess['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(preprocess['Absenteeism Time in Hours']>3,1,0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
preprocess['Absenteeism Excess']=targets

In [8]:
preprocess.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Absenteeism Excess  
0                   1  
1                   0  
2                   0  
3                   1  
4                   0

In [10]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [11]:
data_with_targets = preprocess.drop(['Absenteeism Time in Hours'],axis=1)

In [12]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Excess  
0               30          0         2    1                   1  
1               31          0         1    0                   0  
2               31          0         0    0                   0  
3               24          0         2    0                   1  
4               30          0         2    1                   0

In [14]:
#select the inputs for regression 
data_with_targets.shape

(700, 15)

In [15]:
data_with_targets.iloc[:,0:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pet  
0                 30          0         2    1  
1                 31          0         1    0  
2                 31          0         0    0  
3                 24          0         2    0  
4                 30          0         2    1  
..               ...        ...       ...  ...  
695               22          1         2    0  
696               24          0         1    2  
697               25          1         0    0  
698               25          1         0    0  
699               25          0         1    1  

[700 rows x 14 columns]

In [16]:
unscaled_inputs = data_with_targets.iloc[:,0:14]
unscaled_inputs.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  
0               30          0         2    1  
1               31          0         1    0  
2               31          0         0    0  
3               24          0         2    0  
4               30          0         2    1

In [17]:
#standardise the data 
from sklearn.preprocessing import StandardScaler 

In [18]:
absent_scaler = StandardScaler()

In [19]:
absent_scaler.fit(unscaled_inputs)

StandardScaler()

In [20]:
scaled_inputs = absent_scaler.transform(unscaled_inputs)

In [21]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [22]:
scaled_inputs.shape

(700, 14)

In [23]:
#train test split 
from sklearn.model_selection import train_test_split 

In [24]:
train_test_split(scaled_inputs,targets)

[array([[-0.57735027, -0.09298136,  3.17979734, ...,  2.23224237,
         -0.01928035,  0.26848661],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997,  1.12666297],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
          0.88046927,  0.26848661],
        ...,
        [-0.57735027, -0.09298136,  3.17979734, ..., -0.44798003,
          0.88046927,  0.26848661],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
          0.88046927,  0.26848661],
        [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
         -0.91902997, -0.58968976]]),
 array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  1.12666297],
        [-0.57735027, -0.09298136,  3.17979734, ..., -0.44798003,
         -0.91902997, -0.58968976],
        ...,
        [ 1.73205081, -0.09298136, -0.31448545, ..., -

In [29]:
x_train,x_test,y_train,y_test = train_test_split(scaled_inputs,targets,train_size = 0.8 ,random_state=52)

In [30]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(560, 14)
(140, 14)
(560,)
(140,)


In [31]:
#logistic regression with sklearn 
from sklearn import metrics 
from sklearn.linear_model import LogisticRegression 

In [32]:
#train the model 
reg = LogisticRegression()


In [33]:
reg.fit(x_train,y_train)

LogisticRegression()

In [34]:
reg.score(x_train,y_train)

0.7803571428571429

In [35]:
#manual check for accuracy 
model_outputs = reg.predict(x_train)

In [36]:
model_outputs

array([1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,

In [37]:
y_train

array([1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,

In [38]:
model_outputs == y_train

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True, False,  True,  True, False, False,  True, False,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True,  True,  True, False, False,  True, False,  True,  True,
       False, False,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False,  True,  True,  True,  True, False,
        True,  True,

In [39]:
np.sum(model_outputs == y_train)

437

In [40]:
model_outputs.shape[0]

560

In [41]:
accuracy_check = (437/500)*100
print(round(accuracy_check)," %")

87  %


In [42]:
#finding the intercepts and coeff 
reg.intercept_

array([-0.22780746])

In [44]:
reg.coef_

array([[ 2.13248704,  0.32705895,  1.65842189,  1.39772579, -0.11894605,
        -0.19515371,  0.81964435, -0.13593962, -0.24489623, -0.10034278,
         0.35422261, -0.10166005,  0.51185252, -0.32614864]])

In [45]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [46]:
feature_name = unscaled_inputs.columns.values 

In [49]:
summary_table = pd.DataFrame(columns=['feature_name'],data = feature_name)

In [51]:
summary_table['Coef']=np.transpose(reg.coef_)

In [52]:
summary_table

feature_name      Coef
0                  Reason_1  2.132487
1                  Reason_2  0.327059
2                  Reason_3  1.658422
3                  Reason_4  1.397726
4               Month Value -0.118946
5           Day of the Week -0.195154
6    Transportation Expense  0.819644
7          Distance to Work -0.135940
8                       Age -0.244896
9   Daily Work Load Average -0.100343
10          Body Mass Index  0.354223
11                Education -0.101660
12                 Children  0.511853
13                      Pet -0.326149

In [53]:
summary_table.index = summary_table.index+1

In [57]:
summary_table.loc[0] = ['Intercept',reg.intercept_[0]]

In [58]:
summary_table=summary_table.sort_index()
summary_table

feature_name      Coef
0                 Intercept -0.227807
1                  Reason_1  2.132487
2                  Reason_2  0.327059
3                  Reason_3  1.658422
4                  Reason_4  1.397726
5               Month Value -0.118946
6           Day of the Week -0.195154
7    Transportation Expense  0.819644
8          Distance to Work -0.135940
9                       Age -0.244896
10  Daily Work Load Average -0.100343
11          Body Mass Index  0.354223
12                Education -0.101660
13                 Children  0.511853
14                      Pet -0.326149

In [72]:
#interpret the coeff 
summary_table['Odds_ratio'] = np.exp(summary_table.Coef)

In [75]:
summary_table.sort_values('Odds_ratio',ascending=False)

feature_name      Coef  Odds ratio   Odds_ratio   Odds_ratio
1                  Reason_1  2.132487     8.435821     8.435821    8.435821
3                  Reason_3  1.658422     5.251018     5.251018    5.251018
4                  Reason_4  1.397726     4.045988     4.045988    4.045988
7    Transportation Expense  0.819644     2.269692     2.269692    2.269692
13                 Children  0.511853     1.668379     1.668379    1.668379
11          Body Mass Index  0.354223     1.425072     1.425072    1.425072
2                  Reason_2  0.327059     1.386883     1.386883    1.386883
10  Daily Work Load Average -0.100343     0.904527     0.904527    0.904527
12                Education -0.101660     0.903337     0.903337    0.903337
5               Month Value -0.118946     0.887856     0.887856    0.887856
8          Distance to Work -0.135940     0.872895     0.872895    0.872895
6           Day of the Week -0.195154     0.822708     0.822708    0.822708
0                 Intercept -0.227807     0.796278     0.796278    0.796278
9                       Age -0.244896     0.782786     0.782786    0.782786
14                      Pet -0.326149     0.721698     0.721698    0.721698

In [81]:
#testing the model 
reg.score(x_test,y_test)

0.6928571428571428

In [82]:
predicted_proba = reg.predict_proba(x_test)

In [83]:
predicted_proba

array([[0.12334808, 0.87665192],
       [0.60446704, 0.39553296],
       [0.25039801, 0.74960199],
       [0.82400854, 0.17599146],
       [0.85944075, 0.14055925],
       [0.78023047, 0.21976953],
       [0.44713148, 0.55286852],
       [0.38305511, 0.61694489],
       [0.74201866, 0.25798134],
       [0.77923813, 0.22076187],
       [0.13737312, 0.86262688],
       [0.46594225, 0.53405775],
       [0.28191668, 0.71808332],
       [0.83285916, 0.16714084],
       [0.17151943, 0.82848057],
       [0.73875702, 0.26124298],
       [0.57377511, 0.42622489],
       [0.3052805 , 0.6947195 ],
       [0.08716064, 0.91283936],
       [0.48337904, 0.51662096],
       [0.78634368, 0.21365632],
       [0.60052578, 0.39947422],
       [0.74201866, 0.25798134],
       [0.56716978, 0.43283022],
       [0.45692979, 0.54307021],
       [0.46882645, 0.53117355],
       [0.16790271, 0.83209729],
       [0.56655724, 0.43344276],
       [0.79139933, 0.20860067],
       [0.93382573, 0.06617427],
       [0.

In [84]:
predicted_proba.shape

(140, 2)

In [85]:
#save the model 

In [86]:
import pickle

In [87]:
with open('model','wb') as file:
    pickle.dump(reg,file)

In [90]:
with open('scaler','wb') as file:
    pickle.dump(absent_scaler,file)